### Importing Dataset

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Importing Dataset

In [23]:
dataset = pd.read_csv('P1_BreastCancerData.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
pd.DataFrame(dataset)

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

### Splitting into training set and test set

In [24]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train = train_test_split(x,y,test_size=0.2,random_state=0)

### Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_test = sc.fit_transform(x_test)
x_train= sc.fit_transform(x_train)

### Training k nearest model over training set

In [26]:
from sklearn.neighbors import KNeighborsClassifier
cl_kn = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
cl_kn.fit(x_train,y_train)

KNeighborsClassifier()

### Making Confusion Matrix and predicting accuracy of k nearest neighbour

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_kn = cl_kn.predict(x_test)
print(confusion_matrix(y_test,y_pred_kn))
accuracy_score(y_test,y_pred_kn)

[[350   7]
 [ 11 178]]


0.967032967032967

### Training svm model over training set

In [28]:
from sklearn.svm import SVC
cl_svm = SVC(kernel='linear',random_state=0)
cl_svm.fit(x_train,y_train)

SVC(kernel='linear', random_state=0)

### Making confusion matrix and predicting accuracy of svm

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_svm = cl_svm.predict(x_test)
print(confusion_matrix(y_test,y_pred_svm))
accuracy_score(y_test,y_pred_svm)

[[339  18]
 [  6 183]]


0.9560439560439561

### Training logistic regression model

In [15]:
from sklearn.linear_model import LogisticRegression
cl_lg = LogisticRegression(random_state=0)
cl_lg.fit(x_train,y_train)

LogisticRegression(random_state=0)

### Making confusion matrix and predicting accuracy of logistic regression

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_lg = cl_lg.predict(x_test)
print(confusion_matrix(y_test,y_pred_lg))
accuracy_score(y_test,y_pred_lg)

[[350   7]
 [ 11 178]]


0.9688644688644689

### Training Kernel svm model

In [30]:
from sklearn.svm import SVC
cl_ksvm = SVC(kernel='rbf',random_state=0)
cl_ksvm.fit(x_train,y_train)

SVC(random_state=0)

### Making confusion matrix and predicting accuracy of kernel svm classification

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_ksvm = cl_ksvm.predict(x_test)
print(confusion_matrix(y_test,y_pred_ksvm))
accuracy_score(y_test,y_pred_ksvm)

[[347  10]
 [  8 181]]


0.967032967032967

### Training Naive Bayes model

In [32]:
from sklearn.naive_bayes import GaussianNB
cl_nb = GaussianNB()
cl_nb.fit(x_train,y_train)

GaussianNB()

### Making confusion matrix and predicting accuracy of Naive Bayes classification

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_nb = cl_nb.predict(x_test)
print(confusion_matrix(y_test,y_pred_nb))
accuracy_score(y_test,y_pred_nb)

[[341  16]
 [  4 185]]


0.9633699633699634

### Training decision tree classification model

In [34]:
from sklearn.tree import DecisionTreeClassifier
cl_dt = DecisionTreeClassifier(criterion='entropy',random_state=0)
cl_dt.fit(x_test,y_test)

DecisionTreeClassifier(criterion='entropy', random_state=0)

### Making confusion matrix and predicting accuracy of Decision Tree classification

In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_dt = cl_dt.predict(x_test)
print(confusion_matrix(y_test,y_pred_dt))
accuracy_score(y_test,y_pred_dt)

[[357   0]
 [  0 189]]


1.0

### Training random forest classification model

In [36]:
from sklearn.ensemble import RandomForestClassifier
cl_rf = RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=0)
cl_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

### Making confusion matrix and predicting accuracy of Random Forest classification

In [37]:
from sklearn.metrics import accuracy_score,confusion_matrix
y_pred_rf = cl_rf.predict(x_test)
print(confusion_matrix(y_test,y_pred_rf))
accuracy_score(y_test,y_pred_rf)

[[351   6]
 [ 15 174]]


0.9615384615384616