### Importing Libraries

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

### Importing Dataset

In [9]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values
pd.DataFrame(dataset)

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [10]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [11]:
print(y)

[1 0 1 ... 1 1 0]


### Data Preprocessing

##### Encoding Gender

In [12]:
from sklearn.preprocessing import LabelEncoder
enc = LabelEncoder();
x[:,2] = enc.fit_transform(x[:,2])

In [13]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


##### Encoding Country

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [15]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting Dataset into training and test set

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

### Feature Scaling

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

### Building ANN

##### Initializing ANN

In [22]:
ann = tf.keras.models.Sequential() 

##### Adding input layer and first hidden layer

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

##### Adding second hidden layer

In [24]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

##### Adding output layer

In [25]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

### Training ANN

##### Compiling ANN

In [26]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

##### Training ANN over Training set

In [27]:
ann.fit(x_train,y_train,batch_size=32,epochs=150)

Epoch 1/150
250/250 [==============================] - 8s 4ms/step - loss: 0.4844 - accuracy: 0.7918
Epoch 2/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4498 - accuracy: 0.7961
Epoch 3/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4373 - accuracy: 0.8004
Epoch 4/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4280 - accuracy: 0.8136
Epoch 5/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4208 - accuracy: 0.8186
Epoch 6/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4142 - accuracy: 0.8215
Epoch 7/150
250/250 [==============================] - 1s 3ms/step - loss: 0.4063 - accuracy: 0.8240
Epoch 8/150
250/250 [==============================] - 1s 4ms/step - loss: 0.3973 - accuracy: 0.8250
Epoch 9/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3873 - accuracy: 0.8335
Epoch 10/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3775 - accura

250/250 [==============================] - 1s 3ms/step - loss: 0.3370 - accuracy: 0.8619
Epoch 82/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3370 - accuracy: 0.8636
Epoch 83/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8635
Epoch 84/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3364 - accuracy: 0.8644
Epoch 85/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8637
Epoch 86/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3364 - accuracy: 0.8636
Epoch 87/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8624
Epoch 88/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3362 - accuracy: 0.8643
Epoch 89/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3365 - accuracy: 0.8643
Epoch 90/150
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 

##### Predicting particular data

In [32]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5

1/1 [==============================] - 0s 41ms/step


array([[False]])

### Predicting Test set 

In [34]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 2ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making Confusion Metrics

In [36]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1522   73]
 [ 205  200]]


0.861